veroMain/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('traerActividades/', views.traerActividades, name='traerActividades'),
    path('menu/', views.menu, name='menu')
]

veroMain/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('update/', views.update, name='update')
]

veroMain/vero/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('personalActivities/', include('personalActivities.urls')),
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls')),
    path('experience/', include('experience.urls')),
    path('grupalActivities/', include('grupalActivities.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('weeklyChallenges/', include('weeklyChallenges.urls'))
]

veroMain/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


from personalActivities.models import PersonalActivites
from encuesta.models import Encuesta
from Achievements.models import Achievement
from grupalActivities.models import GroupActivity
# Create your models here.


class User_profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    experience = models.IntegerField(default=0)
    activities = models.ManyToManyField(
        PersonalActivites, through='User_activity')
    group_activities = models.ManyToManyField(GroupActivity)
    completed_group_activities = models.ManyToManyField(GroupActivity, related_name='completed')

    def __str__(self):
        return self.user.username


    

class User_achievements(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)
    date_achieved = models.DateTimeField('date achieved', default=timezone.now)

    class Meta:
        unique_together = ('user','achievement')


class User_activity(models.Model):
    user = models.ForeignKey(User_profile, on_delete=models.CASCADE)
    activity = models.ForeignKey(PersonalActivites, on_delete=models.CASCADE)
    date_start = models.DateTimeField('date start', default=timezone.now)
    date_finish = models.DateTimeField('date finish', null=True, blank=True)
    status = models.CharField(max_length=50, default="started")
    encuesta = models.OneToOneField(
        Encuesta, related_name="activity", on_delete=models.CASCADE, null=True, default=None)

    class Meta:
        verbose_name = ("User_activity")
        verbose_name_plural = ("User_activitys")

    def __str__(self):
        return self.user.user.username + "_" + self.activity.name

    def get_absolute_url(self):
        return reverse("User_activity_detail", kwargs={"pk": self.pk})

veroMain/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User_profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        up = User_profile(user=user)
        if commit:
            user.save()
            up.save()
        return user


class UserLoginForm(AuthenticationForm):
    pass


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

veroMain/users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from django.template import RequestContext
from .forms import UserLoginForm, UserRegisterForm, UserUpdateForm
import datetime
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.serializers import serialize
from django.contrib.auth.models import User
from weeklyChallenges.models import Challenges
from datetime import datetime

# Create your views here.


def registerUser(request):
    if request.user.is_authenticated:
        return redirect('personal_activities_list')
    context = {
        'pageTitle': 'Register',
    }
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = UserRegisterForm()

    context['form'] = form
    return render(request,  'users/register.html', context)


def loginUser(request):
    if request.user.is_authenticated:
        ### Weekly Challenge
        hoy = str(datetime.now().day)
        try:
            ans = Challenges.objects.get(user=request.user)
            ans.name += " " + hoy
            ans.name = set(ans.name.split())
            ans.days = len(ans.name)
            ans.name = " ".join(list(ans.name))
            ans.save()
        except:
            ans = Challenges(user=request.user, days=1,name=hoy)
            ans.save()

        ###
        return redirect('personal_activities_list')
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')

    else:
        form = UserLoginForm()

    context = {
        'pageTitle': 'Login',
        'form': form
    }

    return render(request,  'users/login.html', context)


def logoutUser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')


@login_required
def update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('index')

    else:
        u_form = UserUpdateForm(instance=request.user)

    context = {
        'u_form': u_form,
    }

    return render(request, 'users/update.html', context)

veroMain/users/templates/users/login.html
{% extends 'home/base.html' %}
{% block title %}{{ pageTitle }}{% endblock %}
{%load static %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{%static 'home/css/styleReg.css'%}">
{% endblock %}

{% block content %}
<img class="fondo" src="{%static 'home/img/fondo.png'%}">
<img class="fondo2" src="{%static 'home/img/fondo.png'%}">
<div class="container">
  <!-- Formulario de Registro -->
  <div class="login">
    <form method="post">
      {%csrf_token%}
      <div class="img2">
        <img src="{%static 'home/img/logo.png'%}">
      </div>
      <h2 class="subtitle">Bienvenido a Vero</h2>

      <div class="input-div one">
        <div class="i">
          <i class="fas fa-id-card"></i>
        </div>
        <div class="div">
          <input type="text" name="username" maxlength="150" autofocus="" required id="id_username" placeholder="username">
          
        </div>
      </div>
      
      <div class="input-div pass">
        <div class="i">
          <i class="fas fa-lock"></i>
        </div>
        <div class="div">
          <input type="password" name="password" autocomplete="new-password" required id="id_password" placeholder="contraseña">
        </div>
      </div>
      <button id="Registrar" type="submit" class="btn">Iniciar sesión</button>
      <a href="{% url 'users:register' %}" id="Devolver">Crea una cuenta</a><br>
      <div id="userNameHelp" class="form-text">
        {% if form.errors %}
        {% for error in form.non_field_errors %}
        {{ error|escape }}
        {% endfor %}
        {% endif %}
      </div>
    </form>

  </div>
  <div class="img">
    <img src="{%static 'home/img/signinfo.svg'%}">
  </div>
</div>
{% endblock %}

veroMain/users/templates/users/register.html
{% extends 'home/base.html' %}
{% block title %}{{ pageTitle }}{% endblock %}
{%load static %}
{%load crispy_forms_tags %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{%static 'home/css/styleReg.css'%}">
{% endblock %}

{% block content %}
<img class="fondo" src="{%static 'home/img/fondo.png'%}">
<img class="fondo2" src="{%static 'home/img/fondo.png'%}">
<div class="container">
  <!-- Formulario de Registro -->
  <div class="login">
    <form method="post">
      {%csrf_token%}
      <a href="{% url 'index' %}">
        <div class="img2">
          <img src="{%static 'home/img/logo.png'%}">
        </div>
      </a>
      <h2 class="subtitle">Bienvenido a Vero</h2>

      <div class="input-div one">
        <div class="i">
          <i class="fas fa-id-card"></i>
        </div>
        <div class="div">
          <input type="text" name="username" maxlength="150" autofocus="" required id="id_username"
            placeholder="username">
        </div>

      </div>
      <div id="userNameHelp" class="form-text">
        {% if form.username.errors %}
            {% for error in form.username.errors %}
              {{ error|escape }}
            {% endfor %}
        {% endif %}
      </div>

      <div class="input-div one">
        <div class="i">
          <i class="fas fa-envelope"></i>
        </div>
        <div class="div">

          <input type="email" name="email" required id="id_email" placeholder="correo">
        </div>
      </div>
      <div id="emailHelp" class="form-text">
        {% if form.email.errors %}
            {% for error in form.email.errors %}
              {{ error|escape }}
            {% endfor %}
        {% endif %}
      </div>




      <div class="input-div pass">
        <div class="i">
          <i class="fas fa-lock"></i>
        </div>
        <div class="div">
          <input type="password" name="password1" autocomplete="new-password" required id="id_password1"
            placeholder="contraseña">
        </div>
      </div>
      <div id="password1Help" class="form-text">
        {% if form.password1.errors %}
            {% for error in form.password1.errors %}
              {{ error|escape }}
            {% endfor %}
        {% endif %}
      </div>

      <div class="input-div pass">
        <div class="i">
          <i class="fas fa-lock"></i>
        </div>
        <div class="div">

          <input type="password" name="password2" autocomplete="new-password" required id="id_password2"
            placeholder="confirmar contraseña">
        </div>
      </div>
      <div id="password2Help" class="form-text">
        {% if form.password2.errors %}
            {% for error in form.password2.errors %}
              <p>{{ error|escape }}</p>
            {% endfor %}
        {% endif %}
      </div>
      <br>
      <a href="{% url 'users:login' %}" id="Devolver">¿Ya tienes una cuenta? Inicia Sesión</a><br>
      <div class="terminos">
        <input style="opacity:1;" type="checkbox" data-required="1" name="terminos"> Aceptar los<a
          href="PoliticasPrivacidad.html">
          Términos y
          Condiciones
        </a></b>

      </div>
      <button id="Registrar" type="submit" class="btn">Regístrate </button>
    </form>


  </div>
  <div class="img">
    <img src="{%static 'home/img/signinfo.svg'%}">
  </div>
</div>
{% endblock %}

veroMain/users/templates/users/update.html
{% extends 'home/base.html' %}
{% block title %}{{ pageTitle }}{% endblock %}
{%load static %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{%static 'home/css/styleReg.css'%}">
{% endblock %}

{% block content %}
<img class="fondo" src="{%static 'home/img/fondo.png'%}">
<img class="fondo2" src="{%static 'home/img/fondo.png'%}">
<div class="container">
    <!-- Formulario de Registro -->
    <div class="login">
        <form method="post">
            {%csrf_token%}
            <div class="img2">
                <img src="{%static 'home/img/logo.png'%}">
            </div>
            <h2 class="subtitle">Actualiza tus datos</h2>

            <div class="input-div one">
                <div class="i">
                    <i class="fas fa-id-card"></i>
                </div>
                <div class="div">
                    <input type="text" name="username" maxlength="150" autofocus="" required id="id_username" value={{user.username}}>

                </div>
            </div>

            <div class="input-div pass">
                <div class="i">
                    <i class="fas fa-lock"></i>
                </div>
                <div class="div">
                    <input type="email" name="email" required id="id_email" value={{user.email}}>
                </div>
            </div>
            <button id="Registrar" type="submit" class="btn">Actualizar</button>
            <div>
                <button id="Volver" href="index" class="btn">Volver</button>
            </div>
            <div id="userNameHelp" class="form-text">
                {% if form.errors %}
                {% for error in form.non_field_errors %}
                {{ error|escape }}
                {% endfor %}
                {% endif %}
            </div>
        </form>

    </div>
    <div class="img">
        <img src="{%static 'home/img/signinfo.svg'%}">
    </div>
</div>
{% endblock %}