veroMain/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('traerActividades/', views.traerActividades, name='traerActividades'),
    path('menu/', views.menu, name='menu')
]

veroMain/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('update/', views.update, name='update')
]

veroMain/vero/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('personalActivities/', include('personalActivities.urls')),
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls')),
    path('experience/', include('experience.urls')),
    path('grupalActivities/', include('grupalActivities.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('weeklyChallenges/', include('weeklyChallenges.urls'))
]

veroMain/home/models.py
from django.db import models

# Create your models here.

veroMain/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from django.core.serializers import serialize
from personalActivities.models import PersonalActivites


# Create your views here.
def index(request):
    if(request.user.is_authenticated):
        return redirect("menu")

    context = {
        'pageTitle': 'Landing'
    }
    return render(request, "home/landing.html", context)


def menu(request):
    pers = PersonalActivites.objects.all()
    data = serialize('json', pers)
    data = json.loads(data)
    context = {
        'activities': [[x.name, x.description, x.image_URL, x.duration] for x in pers],
        'activities2': pers[:4]
    }
    return render(request, "home/menu.html", context=context)


@csrf_exempt
def traerActividades(request):
    if request.method == 'POST':  # :
        print("Vegetableeeees")
        pers = PersonalActivites.objects.all()
        data = serialize('json', pers)
        data = json.loads(data)
        context = {
            'activities': data
        }
        return render(request, context=context)
    return render(request, context={'status': 400})

veroMain/home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% block head %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="{% static 'home/img/icono.png' %}" width="100" height="100" />
  {% block style %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i"
    rel="stylesheet">
  <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a81368914c.js"></script>

  {% endblock %}
  <title>{% block title %}{% endblock %} | Vero </title>
  {% endblock %}
</head>

<body>
  {% block header %}{% endblock %}
  <main>
    {% block content %}{% endblock %}
  </main>
  {% block footer %}{% endblock %}
  {% block javascript %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a81368914c.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  {% endblock %}
</body>

</html>

veroMain/home/templates/home/footer.html
{% load static %}
<footer>
  <div class="main-content ">

    <div class="left box ">
      <h2> Sobre nosotros </h2>
      <div class="content ">
        <p> Te presentamos a Vero, una plataforma que te brinda espacios de ocio individual y en comunidad en donde
          podrás permitirte descansar, divertirte, aumentar tus conocimientos o relacionarte con otras personas de
          forma desinteresada que tienen tus mismas aficiones, una experiencia que beneficia el descanso mental para
          la salud, bienestar y el disfrute de la cultura.. </p>
        <div class="social ">
          <a href="https://github.com/SebastianSierrajc/devOcean-Vero "><span class="fab fa-github "></span></a>
        </div>
      </div>
    </div>

    <div class="center box ">
      <h2> Contáctanos</h2>
      <div class="content ">
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">michael.pinilla01@correo.usa.edu.co</span>
        </div>
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">jessica.parrado01@correo.usa.edu.co</span>
        </div>
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">lady.salazar01@correo.usa.edu.co</span>
        </div>
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">luis.vejarano01@correo.usa.edu.co</span>
        </div>
      </div>
    </div>

    <div class="right box ">
      <h2> Contáctanos</h2>
      <div class="content ">
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">juan.sierra01@correo.usa.edu.co</span>
        </div>
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">santiago.gutierrez01@correo.usa.edu.co</span>
        </div>
        <div class="email ">
          <span class="fas fa-envelope "></span>
          <span class="text ">santiago.canchila01@correo.usa.edu.co</span>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom ">
    <center>
      <span class="credit ">
        Creado por <a href="# ">Canchila - Gutierrez - Parrado - Pinilla - Salazar B - Sierra - Vejarano|</a>
      </span>
      <span class="far fa-copyright "></span><span> 2021 Todos los Derechos Reservados. </span>
    </center>
  </div>
</footer>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
    class="bi bi-arrow-up-short"></i></a>

veroMain/home/templates/home/header.html
{% load static %}

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center justify-content-between">
    <div class="logo">
      <a href="{% url 'index' %}"><img src="{% static 'home/img/logo.png' %}" alt="" class="img-fluid"></a>
    </div>
    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="#hero">Inicio</a></li>
        <li><a class="nav-link scrollto" href="#about">Sobre nosotros</a></li>
        <li><a class="nav-link scrollto" href="#services">Servicios</a></li>
        {% if not user.is_authenticated %}
        <li><a class="getstarted scrollto" href="{% url 'users:login' %}">Iniciar Sesión</a></li>
        {% else %}
        <li>
          <form action="{% url 'users:logout' %}" method="POST">
            {% csrf_token %}
            <button class="getstarted" type="submit">Salir</button>
          </form>
        </li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->
  </div>
</header><!-- End Header -->

veroMain/home/templates/home/headerMain.html
{% load static %}

<div class="nav-header">
  <div class="brand-logo">
      <a href="{% url 'index' %}">

          <span class="logo-compact"><img src="{% static 'encuesta/images/logo.png' %}" alt=""></span>
          <span class="brand-title">
              <img src="{% static 'encuesta/images/logo-text.png' %}" alt="">
          </span>
      </a>
  </div>
  <div class="brand-logoTwo">
      <a href="{% url 'index' %}">
          <b class="logo-abbr"><img src="{% static 'encuesta/images/vero-icon-white.png'%}" alt=""> </b>
      </a>
  </div>
</div>

<div class="header">
  <div class="header-content clearfix">

      <!--Icono de navegación lateral-->

      <div class="nav-control">
          <div class="hamburger">
              <span class="toggle-icon"><i class="icon-menu"></i></span>
          </div>
      </div>


      <!--Campo de busqueda-->

      <div class="header-left">
          <div class="input-group icons">
              <!--Icono-->
              <div class="input-group-prepend">
                  <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i
                          class="mdi mdi-magnify"></i></span>
              </div>
              <!--Input-->
              <input type="search" class="form-control" placeholder="Búsqueda" aria-label="Search Dashboard">
              <div class="drop-down animated flipInX d-md-none">
                  <form action="#">
                      <input type="text" class="form-control" placeholder="Search">
                  </form>
              </div>
          </div>
      </div>

      <div class="header-right">
          <ul class="clearfix">



              <li class="icons dropdown">

                  <!--Imagen del usuario-->

                  <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                      <span class="activity active"></span>
                      <i class="far fa-user" style="width:20px; height:20px;"></i>
                  </div>

                  <!--Opciones del usuario-->

                  <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                      <div class="dropdown-content-body">
                          <ul>
                              <li>
                                  <a href="{% url 'users:update' %}"><i class="icon-user"></i> <span>Cuenta</span></a>
                              </li>
                              <hr class="my-2">
                              <li>
                                  <form action="{% url 'users:logout' %}" method="POST">
                                      {% csrf_token %}
                                      <button class="btn btn-link" type="submit"><i class="icon-key"></i>
                                          <span>Cerrar sesión</span></button>
                                  </form>
                              </li>
                          </ul>
                      </div>
                  </div>
              </li>
          </ul>
      </div>
  </div>
</div>

veroMain/home/templates/home/landing.html
{% extends 'home/base.html' %}
{% block title %}{{ pageTitle }}{% endblock %}
{% load static %}

{% block header %}
{% include 'home/header.html' %}
{% endblock %}

{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row gy-4">
      <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center">
        <h1>Una plataforma para cuidar tu salud mental</h1>
        <h2>Somos una iniciativa de ayuda para las personas con trabajos que le generen estrés laboral, agotamiento
          físico y mental debido a los cargos que ocupan.</h2>
        <div>
          <a href="{% url 'users:register' %}" class="btn-get-started scrollto">Crear cuenta</a>
        </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img">
        <img src="{% static 'home/img/landing1.svg' %}" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>


</section><!-- End Hero -->

<!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container" data-aos="fade-up">

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li id="CarriselProcess" data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li id="CarriselProcess" data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li id="CarriselProcess" data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="Servicios">
            <div class="Textos">
              <br><br><br><br><br><br>
              <p class="lead text-muted">Nuestro principal objetivo es permitir darte un espacio donde tomar un
                break de la vida laboral.</p>
            </div>
            <img src="{% static 'home/img/muchachaFlor.svg' %}" alt="" class="Servicio">
          </div>
        </div>
        <div class="carousel-item">
          <div class="Servicios">
            <img src="{% static 'home/img/escaleras.svg' %}" alt="" class="Servicio">
            <div class="Textos">
              <br><br><br><br><br><br>
              <p class="lead text-muted">Fortaleciendo tu crecimiento personal de forma entretenida, a cualquier
                hora y en cualquier sitio</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="Servicios">
            <div class="Textos">
              <br><br><br><br><br><br>
              <p class="lead text-muted">Con el tiempo que tú dispongas.</p>
            </div>
            <img src="{% static 'home/img/tiempo.svg' %}" alt="" class="Servicio">
          </div>
        </div>

      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span id="deslisanteCarrusel" class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span id="deslisanteCarrusel" class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>



  </div>
</section><!-- End About Section -->

<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
  <div class="contenedor" data-aos="fade-up">

    <div class="section-title">
      <h2>Servicios</h2>
      <p>¿Qué puedes hacer?</p>
    </div>

    <div class="Servicios">
      <img src="{% static 'home/img/servicios1.svg' %}" alt="" class="Servicio">
      <div class="Textos">
        <br><br>
        <h3><span>1</span>Actividades individuales de relajación. </h3>
        <p class="lead text-muted">Ofrecemos actividades y ejercicios que pueden acomodarse a tu tiempo y a los
          sentimientos o estado anímico en el que te encuentres para generar sistemas de relajación.</p>
        <br>
        <h3><span>2</span>Actividades grupales de relajación.</h3>
        <p class="lead text-muted"> Ofrecemos actividades y ejercicios que pueden realizarse a nivel grupal,
          generando nuevas amistades y compartiendo experiencias para el buen manejo de sentimientos y el estado
          anímico.
        </p>
        <br>
        <h3><span>3</span>Progreso en el manejo de sentimientos.</h3>
        <p class="lead text-muted">Podrás ver tu estado anímico a través del tiempo y cómo reaccionas a el, antes y
          después de los ejercicios tanto individuales como grupales propuestos.
        </p>
      </div>
    </div>
    <div class="Servicios">
      <div class="Textos">
        <br><br>
        <h3><span>4</span>Historial de actividades individuales realizadas</h3>
        <p class="lead text-muted"> Ver todas las actividades individuales en los que te postulaste para saber cómo
          es tu progreso en estos, o ver los avances y ejercicios hechos.</p>
        <br>
        <h3><span>5</span>Historial de actividades grupales realizadas</h3>
        <p class="lead text-muted"> Ver todas las actividades grupales en las que te postulaste para saber cómo es
          tu progreso en estos, las personas que participaron y ver los avances y ejercicios hechos.
        </p>
        <br>
        <h3><span>6</span>Progreso y recompensas.</h3>
        <p class="lead text-muted">Podrás revisar tus metas alcanzadas y la mejora a nivel anímico que has logrado
          presentar a través del tiempo.
        </p>
      </div>
      <img src="{% static 'home/img/servicios2.svg' %}" alt="" class="Servicio2">
    </div>

  </div>
</section><!-- End Services Section -->
{% endblock %}

{% block footer %}
{% include 'home/footer.html' %}
{% endblock %}

veroMain/home/templates/home/lateralMenu.html
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
            <li class="nav-label">Menú Principal</li>
            <li>
                <a href="/../" aria-expanded="false">
                    <i class="icon-speedometer menu-icon"></i><span class="nav-text">Home</span>
                </a>
            </li>

            <li class="nav-label">Actividades</li>
            <li>
                <a href="{% url 'personal_activities_list' %}" aria-expanded="false">
                    <i class="fa fa-user"></i><span class="nav-text">Actividades Individuales</span>
                </a>
            </li>
            <li>
                <a href="{% url 'filtroActividadesgrupales' %}" aria-expanded="false">
                    <i class="fa fa-users"></i><span class="nav-text">Actividades Grupales</span>
                </a>
            </li>
            <li>
                <a href="{% url 'grupalActivities' %}" aria-expanded="false">
                    <i class="fa fa-user-plus"></i><span class="nav-text">Crear Actividad grupal</span>
                </a>
            </li>
            <li>
                <a href="{% url 'myActivities' %}" aria-expanded="false">
                    <i class="fa fa-list-alt"></i><span class="nav-text">Mis Actividades grupales</span>
                </a>
            </li>
            <li>
                <a href="{% url 'recommendations' %}" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">Recomendaciones</span>
                </a>
            </li>
            <li>
                <a href="./#" aria-expanded="false">
                    <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Crear Campeonato</span>
                </a>
            </li>

            {% if user.is_staff %}
            <li class="nav-label">Stats</li>
            <li>
                <a href="{% url 'dashboard' %}" aria-expanded="false">
                    <i class="icon-graph menu-icon"></i><span class="nav-text">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{% url 'especialEventForm' %}" aria-expanded="false">
                    <i class="fa fa-list-alt"></i><span class="nav-text">Creacion Eventos</span>
                </a>
            </li>
            {% endif %}
            <li class="nav-label">Mi Perfil</li>

            <li>
                <a href="./#" aria-expanded="false">
                    <i class="icon-menu menu-icon"></i><span class="nav-text">Historial de mis Actividades</span>
                </a>
            </li>
            <li>
                <a href="{% url 'weeklyChallenges' %}" aria-expanded="false">
                    <i class="icon-notebook menu-icon"></i><span class="nav-text">Desafíos semanales</span>
                </a>
            </li>
            <li>
                <a href="{% url 'experience' %}" aria-expanded="false">
                    <i class="icon-graph menu-icon"></i><span class="nav-text">Mi Experiencia</span>
                </a>
            </li>
            <li class="nav-label">Cuenta</li>
            <li>
                <a href="{% url 'users:update' %}" aria-expanded="false">
                    <i class="icon-note menu-icon"></i><span class="nav-text">Configuración de Cuenta</span>
                </a>
            </li>
        </ul>
    </div>
</div>

veroMain/home/templates/home/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Vero - Actividades individuales</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'home/img/fav-icono.png' %}">
    <link href="{% static 'personalActivities/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'personalActivities/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/styleMenu.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
</head>

<body>

    <!--Animación de carga inicial-->

    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>


    <!-- Navegación del header -->
    <div id="main-wrapper" class="show menu-toggle">

        {% include 'home/headerMain.html' %}


        <!--Barra de navegación lateral EDITAR-->

        {% include 'home/lateralMenu.html' %}



        <!--Contenido del cuerpo-->
        {% block content %}
        <section id="menuSection">
            <div class="card">
                <div class="card-body">
                    <h4 class="title_principal">Eventos sugeridos</h4>
                </div>
            </div>
            <div class="container">
                {% for activity in activities2 %}
                <div class="cardMenu">
                    <a href="{% url 'single_activity_selection' activity.id %}">
                        <h2>{{activity.name}}</h2>
                        <h3>{{activity.description}}</h3>
                        <div class="detail">
                            <img src="{{activity.image_URL}}" alt="imagen">
                            <h3>Durante {{activity.duration}}</h3>
                        </div>
                    </a>
                </div>

                {% endfor %}
            </div>
            
            <br>
            <div class="card">
                <div class="card-body">
                    <h4 class="title_principal">Recomendación del momento</h4>
                </div>
            </div>

            <div class="container">
                {% for activity in activities2 %}
                <div class="cardMenu">
                    <a href="{% url 'single_activity_selection' activity.id %}">
                        <h2>{{activity.name}}</h2>
                        <h3>{{activity.description}}</h3>
                        <div class="detail">
                            <img src="{{activity.image_URL}}" alt="imagen">
                            <h3>Durante {{activity.duration}}</h3>
                        </div>
                    </a>
                </div>

                {% endfor %}
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="title_principal">Hacer de nuevo</h4>
                </div>
            </div>

            <div class="container">

                {% for activity in activities2 %}
                <div class="cardMenu">
                    <a href="{% url 'single_activity_selection' activity.id %}">
                        <h2>{{activity.name}}</h2>
                        <h3>{{activity.description}}</h3>
                        <div class="detail">
                            <img src="{{activity.image_URL}}" alt="imagen">
                            <h3>Durante {{activity.duration}}</h3>
                        </div>
                    </a>
                </div>

                {% endfor %}


            </div>
        </section>
        <!-- End Menu -->
        {% endblock %}


        <!-- ======= Footer ======= -->
        <footer>

            <div class="main-content">

                <div class="left box ">
                    <h2> Sobre nosotros </h2>
                    <div class="content">
                        <p> Te presentamos a Vero, una plataforma que te brinda espacios de ocio individual y en
                            comunidad en donde podrás permitirte descansar, divertirte, aumentar tus conocimientos o
                            relacionarte con otras personas de forma desinteresada que tienen tus mismas aficiones, una
                            experiencia que beneficia el descanso mental para la salud, bienestar y el disfrute de la
                            cultura.. </p>
                        <div class="social ">
                            <a href="https://github.com/SebastianSierrajc/devOcean-Vero "><span
                                    class="fab fa-github "></span></a>
                        </div>
                    </div>
                </div>

                <div class="center box ">
                    <h2> Contáctanos</h2>
                    <div class="content ">
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">michael.pinilla01@correo.usa.edu.co</span>
                        </div>
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">jessica.parrado01@correo.usa.edu.co</span>
                        </div>
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">lady.salazar01@correo.usa.edu.co</span>
                        </div>
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">luis.vejarano01@correo.usa.edu.co</span>
                        </div>
                    </div>
                </div>

                <div class="right box ">
                    <h2> Contáctanos</h2>
                    <div class="content ">
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">juan.sierra01@correo.usa.edu.co</span>
                        </div>
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">santiago.gutierrez01@correo.usa.edu.co</span>
                        </div>
                        <div class="email ">
                            <span class="fas fa-envelope "></span>
                            <span class="text ">santiago.canchila01@correo.usa.edu.co</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom ">
                <center>
                    <span class="credit ">
                        Creado por <a href="# ">Canchila - Gutierrez - Parrado - Pinilla - Salazar B - Sierra -
                            Vejarano|</a>
                    </span>
                    <span class="far fa-copyright "></span><span> 2021 Todos los Derechos Reservados. </span>
                </center>
            </div>
        </footer>

    </div>

    <!--Scripts-->
    <script src="{% static 'home/js/common.min.js' %}"></script>
    <script src="{% static 'home/js/custom.min.js' %}"></script>
    <script src="{% static 'home/js/settings.js' %}"></script>
    <script src="{% static 'home/js/gleek.js' %}"></script>
    <script src="{% static 'home/js/styleSwitcher.js' %}"></script>


</body>

</html>